#spring:
# application:
#   name: ms-patien
# profiles:
#   active: dev
# config:
#   import: optional:configserver:http://localhost:8888

#logging:
# level:
#   org.springframework.cloud: DEBUG

#server:
# port: 8081
